# Generated by Django 5.2.6 on 2025-12-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Gönderen Adı')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil Ayarları',
                'verbose_name_plural': 'Profil Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Adınız Soyadınız')),
                ('title', models.CharField(max_length=100, verbose_name='Ünvan')),
                ('bio', models.TextField(verbose_name='Hakkımda Yazıs')),
                ('image', models.ImageField(blank=True, upload_to='profile/', verbose_name='Profil Fotoğrafı')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV Dosyası')),
                ('github_link', models.URLField(blank=True, verbose_name='GitHub Linki')),
                ('linkedin_link', models.URLField(blank=True, verbose_name='Linkedin Linki')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil Ayarları',
                'verbose_name_plural': 'Profil Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Proje Başlığı')),
                ('description', models.TextField(verbose_name='Proje Açıklaması')),
                ('image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Proje Görseli')),
                ('tags', models.CharField(help_text='Virgülle ayırın', max_length=100, verbose_name='Etiketler (Örn: Django, React)')),
                ('live_link', models.URLField(blank=True, verbose_name='Canlı Site Linki')),
                ('source_link', models.URLField(blank=True, verbose_name='Kaynak Kodu Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil Ayarları',
                'verbose_name_plural': 'Profil Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yetenek')),
                ('level', models.IntegerField(default=0, help_text='0-100 arası bir değer girin', verbose_name='Yüzde (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sitede Göster')),
            ],
            options={
                'verbose_name': 'Profil Ayarları',
                'verbose_name_plural': 'Profil Ayarları',
            },
        ),
    ]
