# Generated by Django 5.2.6 on 2025-12-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'İletişim Mesajı', 'verbose_name_plural': 'İletişim Mesajları'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Yetenekı', 'verbose_name_plural': 'Yetenekler'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
    ]
