# Generated by Django 5.2.6 on 2025-12-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Yazılım Dili'), ('framework', 'Framework / Kütüphane')], default='language', max_length=20, verbose_name='Kategori'),
        ),
    ]
