# Generated by Django 5.2.6 on 2025-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='Okul Adı')),
                ('major', models.CharField(max_length=50, verbose_name='Bölüm Adı')),
                ('duration', models.CharField(max_length=50, verbose_name='Süre (Örn: 2020 - 2024)')),
                ('grade', models.CharField(blank=True, max_length=25, verbose_name='Not ortalaması (Opsiyonel)')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Şirket Adı')),
                ('position', models.CharField(max_length=50, verbose_name='Pozisyon')),
                ('duration', models.CharField(max_length=50, verbose_name='Çalışma Süresi')),
                ('descreption', models.TextField(verbose_name='İş Tanımı / Açıklama')),
            ],
            options={
                'verbose_name': 'Deneyim',
                'verbose_name_plural': 'Deneyimler',
            },
        ),
    ]
