# Generated by Django 5.2.6 on 2025-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Örn: Örn: fa-brands fa-python', max_length=25, verbose_name='İkon (FontAwesome)'),
        ),
    ]
