# Generated by Django 5.2.6 on 2025-12-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Yazılım Dili'), ('framework', 'Framework / Kütüphane'), ('tool', 'Araç / Platform')], default='language', max_length=20, verbose_name='Kategori'),
        ),
    ]
