# Generated by Django 5.2.6 on 2025-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-posta Adresi'),
        ),
    ]
