# Generated by Django 5.2.6 on 2025-12-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Sertifika Adı')),
                ('issuer', models.CharField(max_length=50, verbose_name='Veren Kurum (Örn: Udemy, Coursera)')),
                ('date', models.DateField(verbose_name='Alınma Tarihi')),
                ('link', models.URLField(blank=True, verbose_name='Sertifika Linki (Opsiyonel)')),
            ],
            options={
                'verbose_name': 'Sertifika',
                'verbose_name_plural': 'Sertifikalar',
            },
        ),
    ]
