# Generated by Django 5.2.6 on 2025-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bölüm Adı'),
        ),
    ]
