# Generated by Django 5.2.6 on 2025-12-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sıralama (Örn: 1, 2, 3)'),
        ),
    ]
