# Generated by Django 5.2.6 on 2025-12-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['order'], 'verbose_name': 'Sertifika', 'verbose_name_plural': 'Sertifikalar'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order'], 'verbose_name': 'Eğitim', 'verbose_name_plural': 'Eğitim Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order'], 'verbose_name': 'Deneyim', 'verbose_name_plural': 'Deneyimler'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sıralama (Örn: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sıralama (Örn: 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sıralama (Örn: 1, 2, 3)'),
        ),
    ]
