# Generated by Django 5.2.6 on 2025-12-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_certificate_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['order', '-date'], 'verbose_name': 'Sertifika', 'verbose_name_plural': 'Sertifikalar'},
        ),
    ]
