# Generated by Django 5.2.6 on 2025-12-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_certificate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome kodu (örn: fa-brands fa-python) VEYA resim linki (https://...)', max_length=500, verbose_name='İkon (FontAwesome veya Resim Linki)'),
        ),
    ]
