# Generated by Django 5.2.6 on 2025-12-07 08:11

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects/thumbnails/', verbose_name='Thumbnail Görseli'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects/', verbose_name='Proje Görseli'),
        ),
    ]
