# Generated by Django 5.2.6 on 2025-12-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_projectimage_thumbnail_alter_projectimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/', verbose_name='Proje Görseli'),
        ),
    ]
